### ISSUE TITLE
TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by jtblin** [ivpusic/koa-bunyan#4]
Due to https://github.com/ivpusic/koa-bunyan/blob/master/lib/koa-bunyan.js#L20

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/koa-bunyan/pull/6

**Comment by blitzd** [comment]
@ivpusic Your NPM deployed version of this still has the problem.

**Comment by maumercado** [comment]
Still has it Dec 1st 2017
